---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUNpMZPWAmHztGX2wS6J+ORmpXpeEwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMjAwMjI2MTUxNDAwWhcNMjUwMjI0MTUxNDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AOAbWmDQ7mxtmd7bNkIZ6RIe5an8IZCyidJdS3JHPgXXxDxrHz0gZndci4ThLFi0
    8YSYHFldZII44LgwctOc0l1EMnS3il6xA8sFgs1TvvFbiszP/cX8BkbuhmTLZsYp
    oIF6L9XdAeGOOntyWXm9O+NX5sXsM/339o6F3FlZ6156ahxGZ8EcwUZfZ8/xFXd2
    rni5CC4EAiUL7LiX/Z0/lyZ8sJaXg04mEvHwNKKjDu2MyDfBT4VW/Z0seWB325NT
    kIgsmhumLflvPjIl/4IC1c/blS/5VcE60I5cNyXcRLk0LDgN8vaSTC/d2l3Z9R7i
    X8lKqWW9hXomWcItrXzt2QK0xdiUKyCEUUprmPzSbfmWh+4PGIBjxIRpiYNMtUEl
    2x5FIxOTe9uHWDcj2wgOps49E69QGy/+SSWdXm20hc1/GB8nGNSDujTOAoDSyY6C
    tOF01qwyKX+F6yLgm8ptECL3rXIlKo1zsmgQoWkkKQCfjXjGeHZOEjCT5bPlQCM8
    Rp+6xp5zFZZCwkIzjypx0M15AON5YPbxUJTwzbPvCHkSytV5M3dPk0kIEutyc7SC
    apWLuQp660t5xG7IHrUCa40vb4OjIn2OwcFiNPVHhEZjUe9Xeh1kHAEwcaKG6WI9
    H4+1dO0z3VI24J+rAqkl2ykn2ERZg9mJyWF+lFC7qyLpAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTKVcWtyPjq1E3R
    6gXi4h+U9qOaADANBgkqhkiG9w0BAQ0FAAOCAgEAeC/VwIZVFzQM3qYQXD04sbdF
    SLSNTPuWa+jfTRn9GfPgon/xNTcofhoKwm08dZ+r6ZoCoCsVs10/NOjNCcBx+kJU
    ZC1eiwKTzf2y49t424jnX2uoJGteyMH1Ba9rB9YxHKnN5XjxnNz1BRatfHmNASyj
    CYsN67hQPAv+CXAFBAnIkExOG5RrP2cV13gXGto1Drm3xFY6g79Ade/mtocLW2dU
    iFODliPEWZzuW15slhhtlRk9Z0cFFIhqiljDTg8pSJV5HNNSPvx477iGWEzmrWrh
    hfc3DG0SJwNLFaFSWPQdjeh+u51Csqh4+zgYIHU4chsD6un6nmOD892WbzFmQMqg
    oI3v075whXHSDDDm4+JDgAwrYZwm9jljoA5ssfD5+iNtewLWSr4YuJ6+LVPgAXKg
    0qBKONncJiMHAnLANrQ1+mE4pUeGeboStwedNrvI296SeejVzEDNGKfjxlkjS00A
    eCZ8hM28DkG9R7S5jUg1ozsKeOYCmnlOVknmk+/A/w3zuYmfq7Z5QfjFj2Qbia1p
    pDTHA8rf8YGLfi/XhDKT6ld8Q2PaQySwrWHcAQIJoPGIUvVh11nPucb1jHs+0diM
    63o4orpii8ZnJmIuj2xE7eXRlC+bwmAk2oahqTrLdUeX2y/am7F7rpYp/7uQSHvl
    IapIIUdjBWT0s9opJFU=
    -----END CERTIFICATE-----
    
